openapi: 3.1.0
info:
  title: Behandling Service
  version: 0.0.0
tags: []
paths:
  /api/v1/behandling/{behandlingId}/fakta:
    get:
      operationId: Behandling_fakta
      parameters:
        - name: behandlingId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fakta'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    BestemmelseEllerGrunnlag:
      type: object
      required:
        - nøkkel
        - beskrivelse
      properties:
        nøkkel:
          type: string
        beskrivelse:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Fakta:
      type: object
      required:
        - perioder
      properties:
        perioder:
          type: array
          items:
            $ref: '#/components/schemas/Periode'
    Periode:
      type: object
      required:
        - id
        - fom
        - tom
        - feilutbetaltBeløp
        - splittbarePerioder
        - rettsligGrunnlag
      properties:
        id:
          type: string
        fom:
          type: string
          format: date-time
        tom:
          type: string
          format: date-time
        feilutbetaltBeløp:
          type: integer
          format: uint32
        splittbarePerioder:
          type: array
          items:
            type: object
            required:
              - id
              - fom
              - tom
              - feilutbetaltBeløp
              - rettsligGrunnlag
            properties:
              id:
                type: string
              fom:
                type: string
                format: date-time
              tom:
                type: string
                format: date-time
              feilutbetaltBeløp:
                type: integer
                format: uint32
              rettsligGrunnlag:
                type: array
                items:
                  $ref: '#/components/schemas/RettsligGrunnlag'
            description: The template for omitting properties.
        rettsligGrunnlag:
          type: array
          items:
            $ref: '#/components/schemas/RettsligGrunnlag'
    RettsligGrunnlag:
      type: object
      required:
        - bestemmelse
        - grunnlag
      properties:
        bestemmelse:
          $ref: '#/components/schemas/BestemmelseEllerGrunnlag'
        grunnlag:
          $ref: '#/components/schemas/BestemmelseEllerGrunnlag'
