openapi: 3.1.0
info:
  title: Behandling Service
  version: 0.0.0
tags:
  - name: behandling
paths:
  /api/v1/behandling/{behandlingId}/feilutbetaling:
    get:
      operationId: fakta
      parameters:
        - name: behandlingId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FaktaOmFeilutbetaling'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      tags:
        - behandling
components:
  schemas:
    BestemmelseEllerGrunnlag:
      type: object
      required:
        - nøkkel
        - beskrivelse
      properties:
        nøkkel:
          type: string
        beskrivelse:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    FaktaOmFeilutbetaling:
      type: object
      required:
        - feilutbetaling
        - muligeRettsligGrunnlag
        - perioder
        - vurdering
      properties:
        feilutbetaling:
          $ref: '#/components/schemas/Feilutbetaling'
        tidligereVarsletBeløp:
          type: integer
          format: uint32
        muligeRettsligGrunnlag:
          type: array
          items:
            $ref: '#/components/schemas/MuligeRettsligGrunnlag'
        perioder:
          type: array
          items:
            $ref: '#/components/schemas/FaktaPeriode'
        vurdering:
          $ref: '#/components/schemas/Vurdering'
    FaktaPeriode:
      type: object
      required:
        - id
        - fom
        - tom
        - feilutbetaltBeløp
        - splittbarePerioder
        - rettsligGrunnlag
      properties:
        id:
          type: string
        fom:
          type: string
          format: date
        tom:
          type: string
          format: date
        feilutbetaltBeløp:
          type: integer
          format: uint32
        splittbarePerioder:
          type: array
          items:
            type: object
            required:
              - id
              - fom
              - tom
              - feilutbetaltBeløp
              - rettsligGrunnlag
            properties:
              id:
                type: string
              fom:
                type: string
                format: date
              tom:
                type: string
                format: date
              feilutbetaltBeløp:
                type: integer
                format: uint32
              rettsligGrunnlag:
                type: array
                items:
                  $ref: '#/components/schemas/RettsligGrunnlag'
            description: The template for omitting properties.
        rettsligGrunnlag:
          type: array
          items:
            $ref: '#/components/schemas/RettsligGrunnlag'
    Feilutbetaling:
      type: object
      required:
        - beløp
        - fom
        - tom
        - revurdering
      properties:
        beløp:
          type: integer
          format: uint32
        fom:
          type: string
          format: date
        tom:
          type: string
          format: date
        revurdering:
          $ref: '#/components/schemas/Revurdering'
    MuligeRettsligGrunnlag:
      type: object
      required:
        - bestemmelse
        - grunnlag
      properties:
        bestemmelse:
          $ref: '#/components/schemas/BestemmelseEllerGrunnlag'
        grunnlag:
          type: array
          items:
            $ref: '#/components/schemas/BestemmelseEllerGrunnlag'
    Oppdaget:
      type: object
      required:
        - dato
        - av
        - beskrivelse
      properties:
        dato:
          type: string
          format: date
        av:
          type: string
          enum:
            - NAV
            - BRUKER
        beskrivelse:
          type: string
    RettsligGrunnlag:
      type: object
      required:
        - bestemmelse
        - grunnlag
      properties:
        bestemmelse:
          type: string
        grunnlag:
          type: string
    Revurdering:
      type: object
      required:
        - årsak
        - vedtaksdato
        - resultat
      properties:
        årsak:
          type: string
        vedtaksdato:
          type: string
          format: date
        resultat:
          type: string
    Vurdering:
      type: object
      required:
        - årsak
        - oppdaget
      properties:
        årsak:
          type: string
        oppdaget:
          $ref: '#/components/schemas/Oppdaget'
